### ISSUE TITLE
[Plan] Typing game

### ISSUE THREAD

**Issue by sosoYim** [hanana1253/typingGame#3]

**Comment by coolchaeyoung** [comment]
### 기능 상세

- enter를 눌렀을 시 input.value와 보여지는 단어가 일치하는지 비교
  - 틀리면 에러 표시
  - 맞다면 input.value 비우고 다음 단어 출력, 남은 단어 수 - 1
- 시간 흐름(mm: ss: ms)
- 단어가 다 끝나면 popup 표시
