### ISSUE TITLE
[Plan] Popup modal

### ISSUE THREAD

**Issue by sosoYim** [hanana1253/typingGame#4]

**Comment by congaweb** [comment]
Yes~~~~

**Comment by congaweb** [comment]
**기능 상세**
- 등수에 맞는 팝업 디자인 및 메시지 띄우기
- 확인 버튼 클릭 시 랭킹 페이지로 이동

**필요 함수**
- 랭킹 중 가장 높은 점수와 현재 점수 비교
- 최고 등수 class toggle
