### ISSUE TITLE
[Plan] Ranking

### ISSUE THREAD

**Issue by sosoYim** [hanana1253/typingGame#5]

**Comment by hanana1253** [comment]
got it!

**Comment by hanana1253** [comment]
# Ranks Page

## 요구사항
- localStorage에 저장되어 있는 기록들을 불러와 1~5위를 보여주는 순위판.
  - 1~5위 중 현재 유저의 기록이 있으면 CSS로 highlight 처리
- 순위판 하단에 지금 게임을 마친 유저의 순위와 기록을 보여준다.
  - 게임을 하기 전 본 페이지에 접속하여 유저의 정보가 없는 경우에는 이 컴포넌트는 생성하지 않는다.
- 메인 페이지로 유도하는 링크.
  - 게임을 마친 유저에게는 'Try Again', 게임을 하기 전 접속한 유저에게는 'Back to Main Page'라고 버튼이 보이게 한다.

## 마크업 구조
- h1, table, div(유저 로그인상태에 따라 동적 생성), a
